name: Deploy to Vercel Hosting on merge
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  PUSHER_APP_ID: ${{ secrets.PUSHER_APP_ID }}
  PUSHER_KEY: ${{ secrets.PUSHER_KEY }}
  PUSHER_SECRET: ${{ secrets.PUSHER_SECRET }}
  PUSHER_CLUSTER: ${{ secrets.PUSHER_CLUSTER }}
on:
  push:
    branches:
      - main
jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install --global vercel@latest
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}

