name: Deploy to Vercel Hosting on merge
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  PUSHER_APP_ID: ${{ secrets.PUSHER_APP_ID }}
  PUSHER_KEY: ${{ secrets.PUSHER_KEY }}
  PUSHER_SECRET: ${{ secrets.PUSHER_SECRET }}
  PUSHER_CLUSTER: ${{ secrets.PUSHER_CLUSTER }}
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_BACKEND_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v3
      - run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}

