name: Deploy to Vercel Hosting on merge
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
on:
  push:
    branches:
      - main
jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_BACKEND_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install --global vercel@latest
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
  deploy-frontend:
    runs-on: ubuntu-latest
    env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_FRONTEND_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install --global vercel@latest
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}

