name: Deploy to Vercel Hosting on merge
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  PUSHER_APP_ID: ${{ secrets.PUSHER_APP_ID }}
  PUSHER_KEY: ${{ secrets.PUSHER_KEY }}
  PUSHER_SECRET: ${{ secrets.PUSHER_SECRET }}
  PUSHER_CLUSTER: ${{ secrets.PUSHER_CLUSTER }}
on:
  push:
    branches:
      - main
jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_BACKEND_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '18.13.0'
      - run: |
          npm install --global vercel@latest
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          cd backend
          npm install
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
  deploy-frontend:
    runs-on: ubuntu-latest
    env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_FRONTEND_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '18.13.0'
      - run: |
          npm install --global vercel@latest
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          cd frontend
          npm install
          npm run build
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
          
